
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 2830482321036
 */
public class FrameCadastrarProduto extends javax.swing.JFrame {

    /**
     * Creates new form FrameCadastrarProduto
     */
    public FrameCadastrarProduto() {
        initComponents();
        
        // preencherComboProdutos();
        
        //cobCadCategoria.setModel((ComboBoxModel<String>) cDAO.getCategoriasNome());

    }
    
    public void preencherComboProdutos(){
        CategoriaDAO cDAO = new CategoriaDAO();
        
        ArrayList<Categoria> lista = cDAO.getCategorias();
        
        int i = 0;
        for(Categoria c: lista){
            cobCadCategoria.addItem(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCadastrarProduto = new javax.swing.JLabel();
        lblCadNome = new javax.swing.JLabel();
        txtCadNome = new javax.swing.JTextField();
        lblCadPreco = new javax.swing.JLabel();
        txtCadPreco = new javax.swing.JTextField();
        lblCadCodigoBarras = new javax.swing.JLabel();
        txtCadCodigoBarras = new javax.swing.JTextField();
        lblCadCategoria = new javax.swing.JLabel();
        cobCadCategoria = new javax.swing.JComboBox();
        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        lblCadEstoque = new javax.swing.JLabel();
        txtCadEstoque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadastrarProduto.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblCadastrarProduto.setText("Cadastrar Produtos");

        lblCadNome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCadNome.setText("Nome:");

        lblCadPreco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCadPreco.setText("Preço:");

        lblCadCodigoBarras.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCadCodigoBarras.setText("Código de Barras:");

        lblCadCategoria.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCadCategoria.setText("Categoria:");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblCadEstoque.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCadEstoque.setText("Estoque:");

        txtCadEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadCodigoBarras)
                    .addComponent(lblCadEstoque)
                    .addComponent(lblCadCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCadNome)
                    .addComponent(txtCadPreco)
                    .addComponent(txtCadCodigoBarras)
                    .addComponent(txtCadEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobCadCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblCadPreco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblCadNome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnVoltar)
                            .addComponent(lblCadastrarProduto)
                            .addComponent(btnCadastrar))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblCadastrarProduto)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCadNome)
                    .addComponent(txtCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCadPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadPreco))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCadCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCadEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cobCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCadCodigoBarras)
                        .addGap(18, 18, 18)
                        .addComponent(lblCadEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCadCategoria)))
                .addGap(154, 154, 154)
                .addComponent(btnCadastrar)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        String nome = txtCadNome.getText();
        if(txtCadPreco.getText().contains(",")){
            txtCadPreco.setText(txtCadPreco.getText().replace(",", "."));
        }
        float preco = Float.parseFloat(txtCadPreco.getText());
        String codigoBarras = txtCadCodigoBarras.getText();
        int estoque = Integer.parseInt(txtCadEstoque.getText());
        //Pegando o ID
        Categoria c = (Categoria) cobCadCategoria.getSelectedItem();
        
        int idCategoria = c.getId();
        
        if (nome.equals("") || preco <= 0 || codigoBarras.equals("") || estoque < 0){
            JOptionPane.showMessageDialog(null, "Há campos vazios ou incorretos, por favor corrija", "Campo vazio", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            
            Produto p = new Produto(nome, preco, codigoBarras, estoque, idCategoria);
            ProdutoDAO pDAO = new ProdutoDAO();
            pDAO.inserir(p);
            
            txtCadNome.setText("");
            txtCadPreco.setText("");
            txtCadCodigoBarras.setText("");
            txtCadEstoque.setText("");
        }
        
        
        
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtCadEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox cobCadCategoria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCadCategoria;
    private javax.swing.JLabel lblCadCodigoBarras;
    private javax.swing.JLabel lblCadEstoque;
    private javax.swing.JLabel lblCadNome;
    private javax.swing.JLabel lblCadPreco;
    private javax.swing.JLabel lblCadastrarProduto;
    private javax.swing.JTextField txtCadCodigoBarras;
    private javax.swing.JTextField txtCadEstoque;
    private javax.swing.JTextField txtCadNome;
    private javax.swing.JTextField txtCadPreco;
    // End of variables declaration//GEN-END:variables
}
