
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2830482321036
 */
public class FrameExibirProduto extends javax.swing.JFrame {

    /**
     * Creates new form FrameExibirProduto
     */
    public FrameExibirProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblExiProduto = new javax.swing.JLabel();
        lblExiId = new javax.swing.JLabel();
        txtExiId = new javax.swing.JTextField();
        lblExiNome = new javax.swing.JLabel();
        txtExiNome = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        lblExiPreco = new javax.swing.JLabel();
        txtExiPreco = new javax.swing.JTextField();
        lblExiCodigoBarras = new javax.swing.JLabel();
        txtExiCodigoBarras = new javax.swing.JTextField();
        lblExiCategoria = new javax.swing.JLabel();
        txtExiCategoria = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        lblExiEstoque = new javax.swing.JLabel();
        txtExiEstoque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblExiProduto.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExiProduto.setText("Exibir Produto");

        lblExiId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExiId.setText("ID:");

        lblExiNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExiNome.setText("Nome:");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblExiPreco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExiPreco.setText("Preço:");

        txtExiPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExiPrecoActionPerformed(evt);
            }
        });

        lblExiCodigoBarras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExiCodigoBarras.setText("Codigo de Barras:");

        txtExiCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExiCodigoBarrasActionPerformed(evt);
            }
        });

        lblExiCategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExiCategoria.setText("Categoria:");

        txtExiCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExiCategoriaActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblExiEstoque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExiEstoque.setText("Estoque:");

        txtExiEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExiEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblExiProduto, javax.swing.GroupLayout.Alignment.CENTER))
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExiEstoque)
                            .addComponent(lblExiCategoria)
                            .addComponent(lblExiCodigoBarras)
                            .addComponent(lblExiPreco)
                            .addComponent(lblExiNome)
                            .addComponent(lblExiId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExiEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExiCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(195, 195, 195))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExiId, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExiNome, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExiPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExiCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblExiProduto)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExiId)
                    .addComponent(txtExiId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExiNome)
                    .addComponent(txtExiNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExiPreco)
                    .addComponent(txtExiPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExiCodigoBarras)
                    .addComponent(txtExiCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExiEstoque)
                    .addComponent(txtExiEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExiCategoria)
                    .addComponent(txtExiCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltar)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtExiPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExiPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExiPrecoActionPerformed

    private void txtExiCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExiCodigoBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExiCodigoBarrasActionPerformed

    private void txtExiCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExiCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExiCategoriaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        int idProduto = Integer.parseInt(txtExiId.getText());
        
        
        ProdutoDAO pDAO = new ProdutoDAO();
        Produto p = pDAO.getProduto(idProduto);
        
        CategoriaDAO cDAO = new CategoriaDAO();

        Categoria c = cDAO.getCategoria(p.getIdCategoria());

        if(p == null){
            txtExiId.setText("");
            txtExiNome.setText("");
            txtExiPreco.setText("");
            txtExiCodigoBarras.setText("");
            txtExiCategoria.setText("");
            
            JOptionPane.showMessageDialog(this, "Produto não encontrado!");
        }
        else{
            txtExiNome.setText(p.getNome());
            txtExiPreco.setText("" + p.getPreco());
            txtExiCodigoBarras.setText("" + p.getCodidgoBarras());
            txtExiEstoque.setText(""+p.getEstoque());
            txtExiCategoria.setText(c.getNome());
            
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtExiEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExiEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExiEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameExibirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameExibirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameExibirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameExibirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameExibirProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblExiCategoria;
    private javax.swing.JLabel lblExiCodigoBarras;
    private javax.swing.JLabel lblExiEstoque;
    private javax.swing.JLabel lblExiId;
    private javax.swing.JLabel lblExiNome;
    private javax.swing.JLabel lblExiPreco;
    private javax.swing.JLabel lblExiProduto;
    private javax.swing.JTextField txtExiCategoria;
    private javax.swing.JTextField txtExiCodigoBarras;
    private javax.swing.JTextField txtExiEstoque;
    private javax.swing.JTextField txtExiId;
    private javax.swing.JTextField txtExiNome;
    private javax.swing.JTextField txtExiPreco;
    // End of variables declaration//GEN-END:variables
}
