
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2830482321036
 */
public class FrameExibirNota extends javax.swing.JFrame {

    /**
     * Creates new form FrameExibirNota
     */
    public FrameExibirNota() {
        initComponents();
    }

    public void preencherTabela(String notaFiscal, String tipo){
        //Criar método de preencher a tabela  
        
        
        NotaDAO nDAO = new NotaDAO();
        NotaProdutoDAO npDAO = new NotaProdutoDAO();
        NotaProduto notaProduto = new NotaProduto();
        
        Nota nota = new Nota();
        
        nota.setNotaFiscal(notaFiscal);
        nota.setTipo(tipo);
        
        notaProduto.setTipo(tipo);
        nota.setId(nDAO.getID(nota));
        
        notaProduto.setNotaId(nota.getId());
        
        
        ArrayList<NotaProduto> lista = npDAO.getProdutosNota(notaProduto);
        
        DefaultTableModel tabelaProdutosNota = (DefaultTableModel) tabExiItensNota.getModel();
        
        
        for(NotaProduto np: lista){
            ProdutoDAO pDAO = new ProdutoDAO(); 
            Produto p = new Produto();
            
            p.setNome(pDAO.getProdutoNome(np.getProdutoID()));
            Object[] obj = new Object[]{
                np.getId(),
                p.getNome(),
                np.getValorUnitario(),
                np.getQuantidade(),
                np.getValorTotal()
                };

                tabelaProdutosNota.addRow(obj);
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblExiNota = new javax.swing.JLabel();
        lblExiTipo = new javax.swing.JLabel();
        cobExiTipo = new javax.swing.JComboBox<>();
        lblExiConstrutor = new javax.swing.JLabel();
        lblExiData = new javax.swing.JLabel();
        txtExiData = new javax.swing.JTextField();
        lblExiValorTotal = new javax.swing.JLabel();
        txtExiValorTotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabExiItensNota = new javax.swing.JTable();
        lblProdutosNota = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lblExiNotaFiscal = new javax.swing.JLabel();
        txtExiNotaFiscal = new javax.swing.JTextField();
        btnExiNota = new javax.swing.JButton();
        txtExiOperador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblExiNota.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblExiNota.setText("Exibir Nota");

        lblExiTipo.setText("Tipo de nota:");

        cobExiTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Entrada", "Saída" }));
        cobExiTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobExiTipoActionPerformed(evt);
            }
        });

        lblExiConstrutor.setText("Escolha o tipo primeiro:");

        lblExiData.setText("Data:");

        txtExiData.setEditable(false);
        txtExiData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblExiValorTotal.setText("Valor Total:");

        txtExiValorTotal.setEditable(false);
        txtExiValorTotal.setText("0.0");

        tabExiItensNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Valor Unitário", "Quantidade", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabExiItensNota.setEnabled(false);
        jScrollPane1.setViewportView(tabExiItensNota);

        lblProdutosNota.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblProdutosNota.setText("Produtos da nota");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProdutosNota))
                .addGap(261, 261, 261))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lblProdutosNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblExiNotaFiscal.setText("Nota Fiscal:");

        btnExiNota.setText("Procurar");
        btnExiNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExiNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnVoltar)
                        .addComponent(lblExiNota))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblExiConstrutor)
                                .addGap(18, 18, 18)
                                .addComponent(txtExiOperador))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblExiTipo)
                                    .addComponent(lblExiValorTotal)
                                    .addComponent(lblExiData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblExiNotaFiscal))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cobExiTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtExiNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtExiData, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtExiValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))))
                        .addGap(27, 27, 27)
                        .addComponent(btnExiNota, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblExiNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExiTipo)
                    .addComponent(cobExiTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExiNotaFiscal)
                    .addComponent(txtExiNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExiNota))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExiData)
                    .addComponent(txtExiData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExiValorTotal)
                    .addComponent(txtExiValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExiConstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExiOperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cobExiTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobExiTipoActionPerformed
        // TODO add your handling code here:

        if(cobExiTipo.getSelectedItem() == "Entrada"){
            lblExiNota.setText("Exibir nota de entrada:");
            lblExiConstrutor.setText("CNPJ do Fornecedor");
            
            txtExiNotaFiscal.setText("");
            txtExiOperador.setText("");
            txtExiValorTotal.setText("");
            txtExiData.setText("");
            
            
        }
        else if(cobExiTipo.getSelectedItem() == "Saída"){
            lblExiNota.setText("Exibir nota de saída:");
            lblExiConstrutor.setText("CPF do Cliente");
            
            txtExiNotaFiscal.setText("");
            txtExiOperador.setText("");
            txtExiValorTotal.setText("");
            txtExiData.setText("");
        }
        else{
            lblExiNota.setText("Exibir nota");
            lblExiConstrutor.setText("Escolha o tipo primeiro:");
            
            txtExiNotaFiscal.setText("");
            txtExiOperador.setText("");
            txtExiValorTotal.setText("");
            txtExiData.setText("");
        }
    }//GEN-LAST:event_cobExiTipoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExiNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExiNotaActionPerformed
        // TODO add your handling code here:]
        if (cobExiTipo.getSelectedItem() == "Selecione"){
            JOptionPane.showMessageDialog(null, "Escolha a opção de nota primeiro", "Notra Inválida", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(txtExiNotaFiscal.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Insira a nota fiscal correspondente", "Campo vazio", JOptionPane.ERROR_MESSAGE);
            }
            else{
                String tipo = (String) cobExiTipo.getSelectedItem();
                NotaDAO nDAO = new NotaDAO();
                
                Nota n = new Nota();
                
                n.setNotaFiscal(txtExiNotaFiscal.getText());
                
                n.setTipo(tipo);
                
                n.setId(nDAO.getID(n));
                
                Nota nota = nDAO.getNota(n);
                

                

                txtExiOperador.setText(nota.getOperador());
                txtExiValorTotal.setText("" + nota.getValorTotal());
                txtExiData.setText(nota.getData());
                
                preencherTabela(nota.getNotaFiscal(), nota.getTipo());
            }

        }
    }//GEN-LAST:event_btnExiNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameExibirNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameExibirNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameExibirNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameExibirNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameExibirNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExiNota;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cobExiTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExiConstrutor;
    private javax.swing.JLabel lblExiData;
    private javax.swing.JLabel lblExiNota;
    private javax.swing.JLabel lblExiNotaFiscal;
    private javax.swing.JLabel lblExiTipo;
    private javax.swing.JLabel lblExiValorTotal;
    private javax.swing.JLabel lblProdutosNota;
    private javax.swing.JTable tabExiItensNota;
    private javax.swing.JTextField txtExiData;
    private javax.swing.JTextField txtExiNotaFiscal;
    private javax.swing.JTextField txtExiOperador;
    private javax.swing.JTextField txtExiValorTotal;
    // End of variables declaration//GEN-END:variables
}
