/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2830482321036
 */
public class FrameInicial extends javax.swing.JFrame {

    /**
     * Creates new form FrameInicial
     */
    public FrameInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javaMenu = new javax.swing.JMenu();
        painelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        radCadCliente = new javax.swing.JRadioButtonMenuItem();
        radCadCategoria = new javax.swing.JRadioButtonMenuItem();
        radCadProduto = new javax.swing.JRadioButtonMenuItem();
        radCadFornecedor = new javax.swing.JRadioButtonMenuItem();
        menuExibir = new javax.swing.JMenu();
        radExiCliente = new javax.swing.JRadioButtonMenuItem();
        radExiCategoria = new javax.swing.JRadioButtonMenuItem();
        radExiProduto = new javax.swing.JRadioButtonMenuItem();
        radExiFornecedor = new javax.swing.JRadioButtonMenuItem();
        menuAtualizar = new javax.swing.JMenu();
        radAtuaCliente = new javax.swing.JRadioButtonMenuItem();
        radAtuaCategoria = new javax.swing.JRadioButtonMenuItem();
        radAtuaProduto = new javax.swing.JRadioButtonMenuItem();
        radAtuaFornecedor = new javax.swing.JRadioButtonMenuItem();
        menuDeletar = new javax.swing.JMenu();
        radDelCliente = new javax.swing.JRadioButtonMenuItem();
        radDelCategoria = new javax.swing.JRadioButtonMenuItem();
        radDelProduto = new javax.swing.JRadioButtonMenuItem();
        radDelFornecedor = new javax.swing.JRadioButtonMenuItem();

        javaMenu.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        menuCadastrar.setText("Cadastrar");

        radCadCliente.setSelected(true);
        radCadCliente.setText("Cliente");
        radCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCadClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(radCadCliente);

        radCadCategoria.setSelected(true);
        radCadCategoria.setText("Categoria");
        radCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCadCategoriaActionPerformed(evt);
            }
        });
        menuCadastrar.add(radCadCategoria);

        radCadProduto.setSelected(true);
        radCadProduto.setText("Produto");
        radCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCadProdutoActionPerformed(evt);
            }
        });
        menuCadastrar.add(radCadProduto);

        radCadFornecedor.setSelected(true);
        radCadFornecedor.setText("Fornecedor");
        menuCadastrar.add(radCadFornecedor);

        jMenuBar1.add(menuCadastrar);

        menuExibir.setText("Exibir");

        radExiCliente.setSelected(true);
        radExiCliente.setText("Cliente");
        radExiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExiClienteActionPerformed(evt);
            }
        });
        menuExibir.add(radExiCliente);

        radExiCategoria.setSelected(true);
        radExiCategoria.setText("Categoria");
        radExiCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExiCategoriaActionPerformed(evt);
            }
        });
        menuExibir.add(radExiCategoria);

        radExiProduto.setSelected(true);
        radExiProduto.setText("Produto");
        menuExibir.add(radExiProduto);

        radExiFornecedor.setSelected(true);
        radExiFornecedor.setText("Fornecedor");
        menuExibir.add(radExiFornecedor);

        jMenuBar1.add(menuExibir);

        menuAtualizar.setText("Atualizar");

        radAtuaCliente.setSelected(true);
        radAtuaCliente.setText("Cliente");
        radAtuaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAtuaClienteActionPerformed(evt);
            }
        });
        menuAtualizar.add(radAtuaCliente);

        radAtuaCategoria.setSelected(true);
        radAtuaCategoria.setText("Categoria");
        menuAtualizar.add(radAtuaCategoria);

        radAtuaProduto.setSelected(true);
        radAtuaProduto.setText("Produto");
        menuAtualizar.add(radAtuaProduto);

        radAtuaFornecedor.setSelected(true);
        radAtuaFornecedor.setText("Fornecedor");
        menuAtualizar.add(radAtuaFornecedor);

        jMenuBar1.add(menuAtualizar);

        menuDeletar.setText("Deletar");

        radDelCliente.setSelected(true);
        radDelCliente.setText("Cliente");
        radDelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDelClienteActionPerformed(evt);
            }
        });
        menuDeletar.add(radDelCliente);

        radDelCategoria.setSelected(true);
        radDelCategoria.setText("Categoria");
        menuDeletar.add(radDelCategoria);

        radDelProduto.setSelected(true);
        radDelProduto.setText("Produto");
        menuDeletar.add(radDelProduto);

        radDelFornecedor.setSelected(true);
        radDelFornecedor.setText("Fornecedor");
        menuDeletar.add(radDelFornecedor);

        jMenuBar1.add(menuDeletar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCadClienteActionPerformed
        // TODO add your handling code here:
        FrameCadastrarCliente frCadCliente = new FrameCadastrarCliente();
        frCadCliente.show();
        //this.visible(false);
    }//GEN-LAST:event_radCadClienteActionPerformed

    private void radExiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExiClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radExiClienteActionPerformed

    private void radAtuaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAtuaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radAtuaClienteActionPerformed

    private void radDelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDelClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radDelClienteActionPerformed

    private void radCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCadCategoriaActionPerformed
        // TODO add your handling code here:
        FrameCadastrarCategoria frCadCategoria = new FrameCadastrarCategoria();
        frCadCategoria.show();
    }//GEN-LAST:event_radCadCategoriaActionPerformed

    private void radExiCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExiCategoriaActionPerformed
        // TODO add your handling code here:
        FrameExibirCategoria frExiCategoria = new FrameExibirCategoria();
        frExiCategoria.show();
    }//GEN-LAST:event_radExiCategoriaActionPerformed

    private void radCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCadProdutoActionPerformed
        // TODO add your handling code here:
        FrameCadastrarProduto frCadProduto = new FrameCadastrarProduto();
        frCadProduto.show();
    }//GEN-LAST:event_radCadProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu javaMenu;
    private javax.swing.JMenu menuAtualizar;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuDeletar;
    private javax.swing.JMenu menuExibir;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JRadioButtonMenuItem radAtuaCategoria;
    private javax.swing.JRadioButtonMenuItem radAtuaCliente;
    private javax.swing.JRadioButtonMenuItem radAtuaFornecedor;
    private javax.swing.JRadioButtonMenuItem radAtuaProduto;
    private javax.swing.JRadioButtonMenuItem radCadCategoria;
    private javax.swing.JRadioButtonMenuItem radCadCliente;
    private javax.swing.JRadioButtonMenuItem radCadFornecedor;
    private javax.swing.JRadioButtonMenuItem radCadProduto;
    private javax.swing.JRadioButtonMenuItem radDelCategoria;
    private javax.swing.JRadioButtonMenuItem radDelCliente;
    private javax.swing.JRadioButtonMenuItem radDelFornecedor;
    private javax.swing.JRadioButtonMenuItem radDelProduto;
    private javax.swing.JRadioButtonMenuItem radExiCategoria;
    private javax.swing.JRadioButtonMenuItem radExiCliente;
    private javax.swing.JRadioButtonMenuItem radExiFornecedor;
    private javax.swing.JRadioButtonMenuItem radExiProduto;
    // End of variables declaration//GEN-END:variables
}
